spring:
  security:
#    user:
#      name: sunjian
#      password: 123456
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://149.129.58.162:3306/new_work?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  rabbitmq:
    virtual-host: /
    host: localhost
    port: 5672
    username: springcloud
    password: 123456
  kafka:
    bootstrap-servers: 47.105.97.246:9092
#    producer:

    consumer:
      group-id: b
      auto-offset-reset: earliest
  data:
    mongodb:
      host: 47.105.97.246
      port: 29017
      database: sj_cluster_test


custom:
  schedule:
    async:
      corePoolSize: 10
      maxPoolSize: 200
      queueCapacity: 10

zookeeper:
  host: 47.105.97.246
  port: 2181
  path: /
  leaderPath: /leader
  lockPath: /lock
  tickTime: 2000
  maxRetries: 5